ar_layers: &id001 []
compute_components_flag: false
config_ar: !!python/object:neuralprophet.configure.AR
  ar_layers: *id001
  ar_reg: 0.1
  n_lags: 30
  reg_lambda: 1.0e-05
config_events: !!python/object/apply:collections.OrderedDict
- - - adultos_mayores
    - !!python/object:neuralprophet.configure.Event
      lower_window: 0
      mode: additive
      reg_lambda: 0.1
      upper_window: 3
  - - discapacidad
    - !!python/object:neuralprophet.configure.Event
      lower_window: 0
      mode: additive
      reg_lambda: 0.1
      upper_window: 3
  - - madres_trabajadoras
    - !!python/object:neuralprophet.configure.Event
      lower_window: 0
      mode: additive
      reg_lambda: 0.1
      upper_window: 3
config_holidays: null
config_lagged_regressors: null
config_normalization: !!python/object:neuralprophet.configure.Normalization
  global_data_params: !!python/object/apply:collections.OrderedDict
  - - - ds
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
        - 39398400000000000
        - 10
        shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
        - 1719792000000000000
        - null
        - null
        - 10
    - - y
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - &id002 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          qqAHON3sD0E=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          3v9FTJzUDkE=
    - - adultos_mayores
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - discapacidad
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - madres_trabajadoras
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
  global_normalization: false
  global_time_normalization: true
  local_data_params: !!python/object/apply:collections.OrderedDict
  - - - JF000436
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 39398400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1719792000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                MPIrHL4yA0E=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                NZKj/JVoA0E=
          - - adultos_mayores
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - discapacidad
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - madres_trabajadoras
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - JF000554
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 39398400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1719792000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                SXncE9+ZG0E=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                Mu8tPtHYG0E=
          - - adultos_mayores
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - discapacidad
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - madres_trabajadoras
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - JF000572
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 39398400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1719792000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                cj74sD1F+EA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                ewQ4vDDQBUE=
          - - adultos_mayores
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - discapacidad
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - madres_trabajadoras
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - JF000584
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 39398400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1719792000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                lGuv5mP7C0E=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                bU7U3dQYD0E=
          - - adultos_mayores
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - discapacidad
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - madres_trabajadoras
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - JF000792
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 39398400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1719792000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                e8azDqm8BUE=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                +e73Z/DuDkE=
          - - adultos_mayores
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - discapacidad
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - madres_trabajadoras
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - JF001046
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 39398400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1719792000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                2bW46sS0C0E=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                NifqbhKXEUE=
          - - adultos_mayores
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - discapacidad
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - madres_trabajadoras
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - JF001129
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 39398400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1719792000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                dtqA3/CXCEE=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                A6N1vuwfDEE=
          - - adultos_mayores
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - discapacidad
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - madres_trabajadoras
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - JF001545
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 39398400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1719792000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                DL+Tm7IRFUE=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                R/mr5SayGEE=
          - - adultos_mayores
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - discapacidad
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - madres_trabajadoras
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - JF001735
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 39398400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1719792000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                tQ8a85kABUE=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                phg0C0zHBEE=
          - - adultos_mayores
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - discapacidad
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - madres_trabajadoras
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - JF001870
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 39398400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1719792000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                mM+8DT4ZAEE=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                F5/EGYLE/0A=
          - - adultos_mayores
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - discapacidad
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - madres_trabajadoras
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
  normalize: standardize
  unknown_data_normalization: false
config_regressors: !!python/object:neuralprophet.configure.ConfigFutureRegressors
  d_hidden: 4
  model: linear
  num_hidden_layers: 2
  regressors: null
config_seasonality: !!python/object:neuralprophet.configure.ConfigSeasonality
  computation: fourier
  condition_name: null
  daily_arg: false
  daily_global_local: auto
  global_local: global
  mode: additive
  periods: !!python/object/apply:collections.OrderedDict
  - - - yearly
      - !!python/object:neuralprophet.configure.Season
        arg: 52
        condition_name: null
        global_local: global
        period: 365.25
        resolution: 52
    - - weekly
      - !!python/object:neuralprophet.configure.Season
        arg: true
        condition_name: null
        global_local: global
        period: 7
        resolution: 3
  reg_lambda: 0.002
  seasonality_local_reg: false
  weekly_arg: true
  weekly_global_local: auto
  yearly_arg: 52
  yearly_global_local: auto
config_train: !!python/object:neuralprophet.configure.Train
  batch_size: 64
  epochs: 200
  lambda_delay: 100
  learning_rate: 0.0035
  loss_func: !!python/object:torch.nn.modules.loss.SmoothL1Loss
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: {}
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: {}
    _non_persistent_buffers_set: !!set {}
    _parameters: {}
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    beta: 0.3
    reduction: none
    training: true
  loss_func_name: SmoothL1Loss
  lr_finder_args: {}
  n_data: 3980
  newer_samples_start: 0.0
  newer_samples_weight: 2
  optimizer: !!python/name:torch.optim.adamw.AdamW ''
  optimizer_args:
    weight_decay: 0.001
  quantiles:
  - 0.5
  reg_delay_pct: 0.5
  reg_lambda_trend: null
  scheduler: !!python/name:torch.optim.lr_scheduler.OneCycleLR ''
  scheduler_args:
    anneal_strategy: cos
    div_factor: 10.0
    final_div_factor: 10.0
    pct_start: 0.3
    three_phase: true
  trend_reg_threshold: null
config_trend: !!python/object:neuralprophet.configure.Trend
  changepoints: null
  changepoints_range: 0.9
  growth: linear
  n_changepoints: 6
  trend_global_local: global
  trend_local_reg: false
  trend_reg: 0.008
  trend_reg_threshold: null
id_list:
- JF001129
- JF000572
- JF000436
- JF000584
- JF001046
- JF000554
- JF000792
- JF001870
- JF001545
- JF001735
lagged_reg_layers: []
max_lags: 30
meta_used_in_model: false
metrics:
  MAE:
  - MeanAbsoluteError
  - {}
  RMSE:
  - MeanSquaredError
  - squared: false
n_forecasts: 30
n_lags: 30
num_seasonalities_modelled: 1
num_seasonalities_modelled_dict: !!python/object/apply:collections.OrderedDict
- - - yearly
    - 1
  - - weekly
    - 1
  - - daily
    - 1
num_trends_modelled: 1
