ar_layers: &id001 []
compute_components_flag: false
config_ar: !!python/object:neuralprophet.configure.AR
  ar_layers: *id001
  ar_reg: 0.1
  n_lags: 30
  reg_lambda: 1.0e-05
config_events: !!python/object/apply:collections.OrderedDict
- - - adultos_mayores
    - !!python/object:neuralprophet.configure.Event
      lower_window: 0
      mode: additive
      reg_lambda: 0.1
      upper_window: 3
  - - discapacidad
    - !!python/object:neuralprophet.configure.Event
      lower_window: 0
      mode: additive
      reg_lambda: 0.1
      upper_window: 3
  - - madres_trabajadoras
    - !!python/object:neuralprophet.configure.Event
      lower_window: 0
      mode: additive
      reg_lambda: 0.1
      upper_window: 3
config_holidays: null
config_lagged_regressors: null
config_normalization: !!python/object:neuralprophet.configure.Normalization
  global_data_params: !!python/object/apply:collections.OrderedDict
  - - - ds
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
        - 39398400000000000
        - 10
        shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
        - 1719792000000000000
        - null
        - null
        - 10
    - - y
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: !!python/object/apply:numpy.core.multiarray.scalar
        - &id002 !!python/object/apply:numpy.dtype
          args:
          - f8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - !!binary |
          Vin2bLUXEkE=
        shift: !!python/object/apply:numpy.core.multiarray.scalar
        - *id002
        - !!binary |
          x7y3+OS4D0E=
    - - adultos_mayores
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - discapacidad
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
    - - madres_trabajadoras
      - !!python/object:neuralprophet.df_utils.ShiftScale
        scale: 1.0
        shift: 0.0
  global_normalization: false
  global_time_normalization: true
  local_data_params: !!python/object/apply:collections.OrderedDict
  - - - JF000157
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 39398400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1719792000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                btj7LapcDUE=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                cpS/Wj7uDUE=
          - - adultos_mayores
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - discapacidad
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - madres_trabajadoras
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - JF000482
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 39398400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1719792000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                JP6UfK5JB0E=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                kyoU/K7rD0E=
          - - adultos_mayores
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - discapacidad
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - madres_trabajadoras
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - JF000555
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 39398400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1719792000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                xiwtTSZiGEE=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                3LgGVLo/GkE=
          - - adultos_mayores
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - discapacidad
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - madres_trabajadoras
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - JF000597
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 39398400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1719792000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                iSWtlXZuHkE=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                6WA75l2SHEE=
          - - adultos_mayores
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - discapacidad
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - madres_trabajadoras
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - JF000604
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 39398400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1719792000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                VafKziJFFUE=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                3LgGVGpiFUE=
          - - adultos_mayores
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - discapacidad
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - madres_trabajadoras
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - JF000667
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 39398400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1719792000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                gRZPIfZL+kA=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                hpAOtuNXAEE=
          - - adultos_mayores
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - discapacidad
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - madres_trabajadoras
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - JF000729
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 39398400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1719792000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                e6jpuK0TBUE=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                9OwR4FAyBEE=
          - - adultos_mayores
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - discapacidad
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - madres_trabajadoras
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - JF001081
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 39398400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1719792000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                TUsEm2Kx60A=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                xaBZYDR58EA=
          - - adultos_mayores
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - discapacidad
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - madres_trabajadoras
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - JF001401
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 39398400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1719792000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                qEnOFY4IBkE=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                SY7yVzOQE0E=
          - - adultos_mayores
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - discapacidad
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - madres_trabajadoras
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
    - - JF001500
      - !!python/object/apply:collections.OrderedDict
        - - - ds
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:pandas._libs.tslibs.timedeltas._timedelta_unpickle
              - 39398400000000000
              - 10
              shift: !!python/object/apply:pandas._libs.tslibs.timestamps._unpickle_timestamp
              - 1719792000000000000
              - null
              - null
              - 10
          - - y
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                OT2WF6KHAUE=
              shift: !!python/object/apply:numpy.core.multiarray.scalar
              - *id002
              - !!binary |
                FpGVzckOA0E=
          - - adultos_mayores
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - discapacidad
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
          - - madres_trabajadoras
            - !!python/object:neuralprophet.df_utils.ShiftScale
              scale: 1.0
              shift: 0.0
  normalize: standardize
  unknown_data_normalization: false
config_regressors: !!python/object:neuralprophet.configure.ConfigFutureRegressors
  d_hidden: 4
  model: linear
  num_hidden_layers: 2
  regressors: null
config_seasonality: !!python/object:neuralprophet.configure.ConfigSeasonality
  computation: fourier
  condition_name: null
  daily_arg: false
  daily_global_local: auto
  global_local: global
  mode: additive
  periods: !!python/object/apply:collections.OrderedDict
  - - - yearly
      - !!python/object:neuralprophet.configure.Season
        arg: 52
        condition_name: null
        global_local: global
        period: 365.25
        resolution: 52
    - - weekly
      - !!python/object:neuralprophet.configure.Season
        arg: true
        condition_name: null
        global_local: global
        period: 7
        resolution: 3
  reg_lambda: 0.002
  seasonality_local_reg: false
  weekly_arg: true
  weekly_global_local: auto
  yearly_arg: 52
  yearly_global_local: auto
config_train: !!python/object:neuralprophet.configure.Train
  batch_size: 64
  epochs: 200
  lambda_delay: 100
  learning_rate: 0.004
  loss_func: !!python/object:torch.nn.modules.loss.SmoothL1Loss
    _backward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _buffers: {}
    _forward_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
    - []
    _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
    - []
    _is_full_backward_hook: null
    _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _modules: {}
    _non_persistent_buffers_set: !!set {}
    _parameters: {}
    _state_dict_hooks: !!python/object/apply:collections.OrderedDict
    - []
    _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
    - []
    beta: 0.3
    reduction: none
    training: true
  loss_func_name: SmoothL1Loss
  lr_finder_args: {}
  n_data: 4180
  newer_samples_start: 0.0
  newer_samples_weight: 2
  optimizer: !!python/name:torch.optim.adamw.AdamW ''
  optimizer_args:
    weight_decay: 0.001
  quantiles:
  - 0.5
  reg_delay_pct: 0.5
  reg_lambda_trend: null
  scheduler: !!python/name:torch.optim.lr_scheduler.OneCycleLR ''
  scheduler_args:
    anneal_strategy: cos
    div_factor: 10.0
    final_div_factor: 10.0
    pct_start: 0.3
    three_phase: true
  trend_reg_threshold: null
config_trend: !!python/object:neuralprophet.configure.Trend
  changepoints: null
  changepoints_range: 0.9
  growth: linear
  n_changepoints: 6
  trend_global_local: global
  trend_local_reg: false
  trend_reg: 0.008
  trend_reg_threshold: null
id_list:
- JF001081
- JF000729
- JF001401
- JF000597
- JF000482
- JF000555
- JF000667
- JF000157
- JF001500
- JF000604
lagged_reg_layers: []
max_lags: 30
meta_used_in_model: false
metrics:
  MAE:
  - MeanAbsoluteError
  - {}
  RMSE:
  - MeanSquaredError
  - squared: false
n_forecasts: 10
n_lags: 30
num_seasonalities_modelled: 1
num_seasonalities_modelled_dict: !!python/object/apply:collections.OrderedDict
- - - yearly
    - 1
  - - weekly
    - 1
  - - daily
    - 1
num_trends_modelled: 1
